checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - tests/*

build:
  environment:
    php:
      version: '8.0'
    variables:
      ELASTICSEARCH_HOST: 'localhost:9200'
      DB_HOST: '127.0.0.1'
      DB_USERNAME: 'root'
      DB_PASSWORD: ''
      DB_DATABASE: 'my_database'
  project_setup:
    before:
      - mysql -e "CREATE DATABASE my_database"
  nodes:
    analysis:
      services:
        elasticsearch: 7.6.1
        mysql: 5.7
      tests:
        override:
          - php-scrutinizer-run
          -
            command: 'vendor/bin/phpunit --coverage-clover=coverage.clover'
            coverage:
              file: 'coverage.clover'
              format: 'clover'
  dependencies:
    override:
      - composer update --no-interaction --no-suggest --prefer-source
